"""Generates exact byte-level character mapping for Chakita/KannadaBERT ByteLevel BPE decoder.
"""

import json
import sys
from pathlib import Path
from transformers import AutoTokenizer

sys.stdout.reconfigure(encoding="utf-8")

tok = AutoTokenizer.from_pretrained("Chakita/KannadaBERT")
vocab = tok.get_vocab()
inv_vocab = {v: k for k, v in vocab.items()}

# Generate GPT-2/RoBERTa bytes_to_unicode mapping
def bytes_to_unicode():
    bs = list(range(ord("!"), ord("~") + 1)) + list(range(ord("¡"), ord("¬") + 1)) + list(range(ord("®"), ord("ÿ") + 1))
    cs = bs[:]
    n = 0
    for b in range(2**8):
        if b not in bs:
            bs.append(b)
            cs.append(2**8 + n)
            n += 1
    return dict(zip(bs, [chr(n) for n in cs]))

b2u = bytes_to_unicode()
u2b = {v: k for k, v in b2u.items()}

# Verify with test string
test_text = "ಕರ್ನಾಟಕ ಭೂಮಿ"
token_ids = tok.encode(test_text, add_special_tokens=False)
token_strings = [inv_vocab[tid] for tid in token_ids]
combined_string = "".join(token_strings)

raw_bytes = bytearray()
for ch in combined_string:
    if ch in u2b:
        raw_bytes.append(u2b[ch])
    else:
        raw_bytes.extend(ch.encode("utf-8"))

decoded_text = raw_bytes.decode("utf-8", errors="replace")
print("Original text:  ", test_text)
print("Decoded text:   ", decoded_text)
assert decoded_text.strip() == test_text.strip(), f"Mismatch! Got {decoded_text} != {test_text}"
print("VERIFICATION SUCCESS: Perfect 100% match with ByteLevel decoding!")

# Export u2b mapping table to frontend
frontend_file = Path("frontend/src/lib/byteLevelDecoder.ts")
frontend_file.parent.mkdir(parents=True, exist_ok=True)

with open(frontend_file, "w", encoding="utf-8") as f:
    f.write("/**\n * Auto-generated ByteLevel mapping table for Chakita/KannadaBERT RoBERTa BPE.\n */\n")
    f.write("export const CHAR_TO_BYTE_MAP: Record<string, number> = " + json.dumps(u2b, indent=2) + ";\n\n")
    f.write("""export function decodeByteLevelTokens(tokenStrings: string[]): string {
  const bytes: number[] = [];
  for (const token of tokenStrings) {
    if (token === '<s>' || token === '</s>' || token === '<pad>' || token === '<unk>') {
      continue;
    }
    for (const char of token) {
      if (char in CHAR_TO_BYTE_MAP) {
        bytes.push(CHAR_TO_BYTE_MAP[char]);
      } else {
        const encoded = new TextEncoder().encode(char);
        for (let i = 0; i < encoded.length; i++) {
          bytes.push(encoded[i]);
        }
      }
    }
  }
  return new TextDecoder('utf-8').decode(new Uint8Array(bytes));
}
""")

print(f"Exported TypeScript decoder to: {frontend_file}")
