"""Generic Multi-Variant Visual Inference & Cross-Variant Beam Aggregation for TrOCR.

Generates multiple aspect-ratio-preserving visual representations of a handwritten crop:
1. Original RGB Crop
2. Grayscale / Contrast-Enhanced (CLAHE) Crop
3. Lightly Sharpened Crop
4. Adaptive-Threshold Cleaned Crop
5. Padded Margin Crop

Executes beam search (num_beams=5) on all variants and performs multi-signal aggregation:
- Cross-variant consensus / agreement
- Acoustic / visual sequence probability
- Orthographic / phonotactic validity
- Lexicon plausibility
"""

from dataclasses import dataclass, field
import unicodedata
from typing import Any, Dict, List, Optional, Tuple

import cv2
import numpy as np
from PIL import Image, ImageOps, ImageFilter

from src.postprocessing.beam_rescorer import KannadaBeamRescorer


@dataclass
class VariantCandidate:
    """A candidate sequence generated by a specific image variant."""
    variant_name: str
    rank: int
    text: str
    token_ids: List[int]
    model_score: float
    model_probability: float


@dataclass
class AggregatedCandidate:
    """An aggregated candidate pooled across all visual variants."""
    text: str
    variants_supported: List[str]
    variant_count: int
    agreement_ratio: float
    mean_model_prob: float
    max_model_prob: float
    orthographic_score: float
    lexicon_score: float
    matched_lexicon_word: Optional[str]
    composite_score: float


@dataclass
class MultiVariantResult:
    """Final output of multi-variant visual inference."""
    final_prediction: str
    confidence: float
    primary_variant_top: str
    primary_variant_confidence: float
    aggregated_top: str
    is_switched: bool
    requires_human_review: bool
    variants_tested: List[str] = field(default_factory=list)
    variant_breakdown: Dict[str, List[Dict[str, Any]]] = field(default_factory=dict)
    all_aggregated_candidates: List[AggregatedCandidate] = field(default_factory=list)


def generate_crop_variants(crop_img: Image.Image) -> Dict[str, Image.Image]:
    """Generates 5 distinct aspect-ratio-preserving image variants for robust visual inference."""
    rgb_img = crop_img.convert("RGB")
    w, h = rgb_img.size
    np_rgb = np.array(rgb_img)

    variants: Dict[str, Image.Image] = {}

    # Variant 1: Original RGB Crop
    variants["1_original_rgb"] = rgb_img

    # Variant 2: Contrast-Enhanced (CLAHE on Grayscale)
    gray = cv2.cvtColor(np_rgb, cv2.COLOR_RGB2GRAY)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    enhanced_gray = clahe.apply(gray)
    variants["2_contrast_clahe"] = Image.fromarray(cv2.cvtColor(enhanced_gray, cv2.COLOR_GRAY2RGB))

    # Variant 3: Lightly Sharpened Crop (Unsharp Masking)
    sharpened_pil = rgb_img.filter(ImageFilter.UnsharpMask(radius=1.5, percent=130, threshold=2))
    variants["3_light_sharpened"] = sharpened_pil

    # Variant 4: Adaptive Thresholding (Ink-cleaned background)
    blurred = cv2.GaussianBlur(gray, (3, 3), 0)
    adapt_bin = cv2.adaptiveThreshold(
        blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 15, 6
    )
    variants["4_adaptive_threshold"] = Image.fromarray(cv2.cvtColor(adapt_bin, cv2.COLOR_GRAY2RGB))

    # Variant 5: Padded Margin Crop (+15px uniform white padding)
    pad = 15
    padded = ImageOps.expand(rgb_img, border=pad, fill="white")
    variants["5_padded_margin"] = padded

    return variants


class MultiVariantBeamEvaluator:
    """Orchestrates multi-variant visual inference and consensus aggregation."""

    def __init__(self, rescorer: Optional[KannadaBeamRescorer] = None):
        self.rescorer = rescorer or KannadaBeamRescorer()

    def run_multi_variant_inference(
        self,
        model: Any,
        processor: Any,
        tokenizer: Any,
        crop_img: Image.Image,
        device: str = "cuda",
        num_beams: int = 5,
    ) -> MultiVariantResult:
        """Executes multi-variant visual beam search and aggregates consensus signals."""
        variants = generate_crop_variants(crop_img)
        variant_names = list(variants.keys())

        variant_candidates: Dict[str, List[VariantCandidate]] = {}
        all_pooled_texts: Dict[str, List[Tuple[str, float, float]]] = {}  # text -> [(variant, model_prob, score)]

        for v_name, v_img in variants.items():
            px = processor(v_img, return_tensors="pt").pixel_values.to(device)
            import torch
            with torch.no_grad():
                outputs = model.generate(
                    px,
                    max_new_tokens=32,
                    num_beams=num_beams,
                    num_return_sequences=num_beams,
                    return_dict_in_generate=True,
                    output_scores=True,
                )

            seq_scores = getattr(outputs, "sequences_scores", None)
            raw_scores = [float(seq_scores[i].item()) if seq_scores is not None else float(-i) for i in range(len(outputs.sequences))]
            max_s = max(raw_scores)
            exp_s = np.exp(np.array(raw_scores) - max_s)
            probs = exp_s / max(1e-8, np.sum(exp_s))

            v_list = []
            for i, seq in enumerate(outputs.sequences):
                text = unicodedata.normalize("NFC", tokenizer.decode(seq, skip_special_tokens=True).strip())
                cand = VariantCandidate(
                    variant_name=v_name,
                    rank=i + 1,
                    text=text,
                    token_ids=seq.tolist(),
                    model_score=raw_scores[i],
                    model_probability=float(probs[i]),
                )
                v_list.append(cand)

                if text not in all_pooled_texts:
                    all_pooled_texts[text] = []
                all_pooled_texts[text].append((v_name, float(probs[i]), raw_scores[i]))

            variant_candidates[v_name] = v_list

        total_variants = len(variants)
        aggregated_list: List[AggregatedCandidate] = []

        for text, occurrences in all_pooled_texts.items():
            if not text:
                continue

            supported_vars = list(set([o[0] for o in occurrences]))
            var_count = len(supported_vars)
            agreement_ratio = var_count / total_variants

            model_probs = [o[1] for o in occurrences]
            mean_prob = float(np.mean(model_probs))
            max_prob = float(np.max(model_probs))

            ortho_score = self.rescorer.check_orthographic_validity(text)
            lex_score, matched_word = self.rescorer.evaluate_lexicon_similarity(text)

            # Combined multi-variant composite scoring:
            # 35% Cross-Variant Agreement + 35% Model Probability + 15% Lexicon Score + 15% Orthography
            composite = (
                0.35 * agreement_ratio
                + 0.35 * mean_prob
                + 0.15 * lex_score
                + 0.15 * ortho_score
            )

            aggregated_list.append(
                AggregatedCandidate(
                    text=text,
                    variants_supported=supported_vars,
                    variant_count=var_count,
                    agreement_ratio=round(agreement_ratio, 4),
                    mean_model_prob=round(mean_prob, 4),
                    max_model_prob=round(max_prob, 4),
                    orthographic_score=round(ortho_score, 4),
                    lexicon_score=round(lex_score, 4),
                    matched_lexicon_word=matched_word,
                    composite_score=round(composite, 4),
                )
            )

        # Sort aggregated candidates by composite score descending
        sorted_aggregated = sorted(aggregated_list, key=lambda c: c.composite_score, reverse=True)
        primary_top = variant_candidates["1_original_rgb"][0].text
        primary_prob = variant_candidates["1_original_rgb"][0].model_probability

        best_aggregated = sorted_aggregated[0] if sorted_aggregated else None

        final_prediction = primary_top
        is_switched = False

        if best_aggregated and best_aggregated.text != primary_top:
            # Only promote alternative if it has strong cross-variant consensus (>= 60% of variants agree)
            # AND superior composite score
            if best_aggregated.variant_count >= 3 and (best_aggregated.composite_score > 0.60):
                final_prediction = best_aggregated.text
                is_switched = True
        elif best_aggregated:
            final_prediction = best_aggregated.text

        final_conf = best_aggregated.composite_score if best_aggregated else 0.50
        requires_review = (
            final_conf < 0.65
            or (best_aggregated and best_aggregated.variant_count < 3)
            or (len(sorted_aggregated) > 1 and abs(sorted_aggregated[0].composite_score - sorted_aggregated[1].composite_score) < 0.04)
        )

        # Format variant breakdown for report
        breakdown_dict = {}
        for v_name, c_list in variant_candidates.items():
            breakdown_dict[v_name] = [
                {
                    "rank": c.rank,
                    "text": c.text,
                    "prob": round(c.model_probability, 4),
                }
                for c in c_list
            ]

        return MultiVariantResult(
            final_prediction=final_prediction,
            confidence=round(final_conf, 4),
            primary_variant_top=primary_top,
            primary_variant_confidence=round(primary_prob, 4),
            aggregated_top=best_aggregated.text if best_aggregated else primary_top,
            is_switched=is_switched,
            requires_human_review=requires_review,
            variants_tested=variant_names,
            variant_breakdown=breakdown_dict,
            all_aggregated_candidates=sorted_aggregated,
        )
